# Generated by Django 4.2 on 2026-04-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_material/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'AUDIO')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses_app.course')),
            ],
            options={
                'db_table': 'course_materials',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
