# Generated by Django 4.2 on 2026-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='file_hash',
            field=models.CharField(default=12, max_length=64),
            preserve_default=False,
        ),
    ]
