# Generated by Django 4.2 on 2026-04-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_coursematerial_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='file_hash',
        ),
    ]
