# Generated by Django 4.2 on 2026-05-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_lesson'),
        ('courses_app', '0004_remove_coursematerial_file_hash'),
    ]

    operations = [
    ]
