# Generated by Django 4.2 on 2026-05-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0005_merge_20260506_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='courses_app.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_assignments',
                'unique_together': {('employee', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'AUDIO'), ('text', 'TEXT'), ('video', 'VIDEO')], max_length=20)),
                ('file', models.FileField(upload_to='course_material/')),
                ('filename', models.CharField(max_length=255)),
                ('text_content', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses_app.lesson')),
            ],
            options={
                'db_table': 'lesson_materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
