# Generated by Django 4.2 on 2026-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_courseassignment_material_delete_coursematerial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='progress_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
