# Generated by Django 4.2 on 2026-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0007_alter_courseassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.AddField(
            model_name='material',
            name='provider_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='provider_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='storage_provider',
            field=models.CharField(default='dropbox', max_length=50),
        ),
    ]
