# Generated by Django 4.2 on 2026-05-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0009_alter_material_filename_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done')], default='not_done', max_length=20),
        ),
    ]
