# Generated by Django 4.2 on 2026-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0010_remove_lessonprogress_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='storage_provider',
            field=models.CharField(default='cloudinary', max_length=50),
        ),
    ]
